// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/home": {
    params: {};
  };
  "/camera": {
    params: {};
  };
  "/analytics": {
    params: {};
  };
  "/api/save-form-data": {
    params: {};
  };
  "/api/update-form-with-camera": {
    params: {};
  };
  "/api/fitness-analysis": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/home" | "/camera" | "/analytics" | "/api/save-form-data" | "/api/update-form-with-camera" | "/api/fitness-analysis";
  };
  "routes/intro.tsx": {
    id: "routes/intro";
    page: "/";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/home";
  };
  "routes/camera.jsx": {
    id: "routes/camera";
    page: "/camera";
  };
  "routes/analytics.tsx": {
    id: "routes/analytics";
    page: "/analytics";
  };
  "routes/api.save-form-data.tsx": {
    id: "routes/api.save-form-data";
    page: "/api/save-form-data";
  };
  "routes/api.update-form-with-camera.tsx": {
    id: "routes/api.update-form-with-camera";
    page: "/api/update-form-with-camera";
  };
  "routes/api.fitness-analysis.tsx": {
    id: "routes/api.fitness-analysis";
    page: "/api/fitness-analysis";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/intro": typeof import("./app/routes/intro.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/camera": typeof import("./app/routes/camera.jsx");
  "routes/analytics": typeof import("./app/routes/analytics.tsx");
  "routes/api.save-form-data": typeof import("./app/routes/api.save-form-data.tsx");
  "routes/api.update-form-with-camera": typeof import("./app/routes/api.update-form-with-camera.tsx");
  "routes/api.fitness-analysis": typeof import("./app/routes/api.fitness-analysis.tsx");
};