// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/home": {
    params: {};
  };
  "/form": {
    params: {};
  };
  "/camera": {
    params: {};
  };
  "/analytics": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/home" | "/form" | "/camera" | "/analytics";
  };
  "routes/intro.tsx": {
    id: "routes/intro";
    page: "/";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/home";
  };
  "routes/form.tsx": {
    id: "routes/form";
    page: "/form";
  };
  "routes/camera.tsx": {
    id: "routes/camera";
    page: "/camera";
  };
  "routes/analytics.tsx": {
    id: "routes/analytics";
    page: "/analytics";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/intro": typeof import("./app/routes/intro.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/form": typeof import("./app/routes/form.tsx");
  "routes/camera": typeof import("./app/routes/camera.tsx");
  "routes/analytics": typeof import("./app/routes/analytics.tsx");
};